name: Sync Hub
on:
  repository_dispatch:
    types: [repo_created]
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Nome do repositório (ex: meu-projeto-etl)'
        required: true

jobs:
  update-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.api_trigger_token }}
          submodules: true

      - name: Run Update Script
        env:
          REPO_NAME: ${{ github.event.client_payload.repo_name || github.event.inputs.repo_name }}
          USER_NAME: ${{ github.repository_owner }}
          API_TOKEN: ${{ secrets.api_trigger_token }}
        run: |
          chmod +x update_hub.sh
          ./update_hub.sh